USE LABORATORIO_BD;

-- etapa 4.1
CREATE TABLE VARONES
SELECT * FROM NACIMIENTOS
WHERE SEXO = 'masculino';
SELECT * FROM VARONES;

CREATE TABLE MUJERES
SELECT * FROM NACIMIENTOS
WHERE SEXO = 'FEMENINO';
SELECT * FROM MUJERES;

CREATE TABLE INDETERMINADO
SELECT * FROM NACIMIENTOS
WHERE SEXO = 'INDETERMINADO';
SELECT * FROM INDETERMINADO;

DROP TABLE NACIMIENTOS;

-- etapa 4.2

SET SQL_SAFE_UPDATES = 0;
UPDATE CLIENTES_NEPTUNO 
SET pais = 'USA'
WHERE pais = 'Estados Unidos';
SELECT * FROM CLIENTES_NEPTUNO;

UPDATE CLIENTES_NEPTUNO
SET NOMBRECOMPANIA = UPPER(NOMBRECOMPANIA);
SELECT * FROM CLIENTES_NEPTUNO;

UPDATE CLIENTES_NEPTUNO
SET CIUDAD = UPPER(CIUDAD), PAIS = UPPER(PAIS);
SELECT * FROM CLIENTES_NEPTUNO;

ALTER TABLE empleados
ADD NOMBRE_EMPLEADO VARCHAR(30);
UPDATE EMPLEADOS
SET NOMBRE_EMPLEADO = CONCAT(APELLIDOS,', ',NOMBRE);
ALTER TABLE EMPLEADOS
DROP APELLIDOS, DROP NOMBRE;
ALTER TABLE EMPLEADOS
CHANGE NOMBRE_EMPLEADO NOMBRE_EMPLEADO VARCHAR(30) AFTER IDEMPLEADO;
SELECT * FROM EMPLEADOS;

ALTER TABLE CLIENTES
ADD TIPO VARCHAR(3);
UPDATE CLIENTES
SET TIPO = 'VIP'
WHERE CIUDAD = 'MADRID';
SELECT * FROM CLIENTES;

ALTER TABLE CLIENTES
MODIFY TELEFONO VARCHAR(20);
UPDATE CLIENTES
SET TELEFONO = CONCAT('+34-',TELEFONO) WHERE TELEFONO IS NOT NULL;
SELECT * FROM CLIENTES;

ALTER TABLE PRODUCTOS ADD FECHA DATE;
UPDATE PRODUCTOS
SET FECHA = CONCAT(ANO,'-',MES,'-',DIA);
ALTER TABLE PRODUCTOS DROP DIA, DROP MES, DROP ANO;
UPDATE PRODUCTOS
SET ORIGEN = 'ESPAÑA' WHERE ORIGEN = 'ESPANA';
SELECT * FROM PRODUCTOS;

ALTER TABLE PRODUCTOS_NEPTUNO MODIFY SUSPENDIDO VARCHAR(2);
UPDATE PRODUCTOS_NEPTUNO
SET SUSPENDIDO = IF(SUSPENDIDO='0','NO','SI');
SELECT * FROM PRODUCTOS_NEPTUNO;

UPDATE PRODUCTOS_NEPTUNO
SET PRECIOUNIDAD = ROUND(PRECIOUNIDAD*1.1,2);
SELECT * FROM PRODUCTOS_NEPTUNO;

SELECT * FROM PROVEEDORES;
UPDATE PROVEEDORES
SET REGION = NULL WHERE REGION = '';

UPDATE CLIENTES
SET CIUDAD = CONCAT(UPPER(LEFT(CIUDAD,1)),LOWER(SUBSTRING(CIUDAD,2,LENGTH(CIUDAD))));
SELECT * FROM CLIENTES;

CREATE TABLE PRODUCTOS_SUSPENDIDOS
SELECT * FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO ='SI';
SELECT * FROM PRODUCTOS_SUSPENDIDOS;

-- ETAPA 4.3
SET AUTOCOMMIT =0;

UPDATE PRODUCTOS_NEPTUNO
SET SUSPENDIDO = 'SI' WHERE IDPROVEEDOR=1;
SELECT * FROM PRODUCTOS_NEPTUNO;

INSERT INTO PRODUCTOS_SUSPENDIDOS (IDPRODUCTO,NOMBREPRODUCTO,NOMBRECONTACTO,NOMBRECATEGORIA,PRECIOUNIDAD,SUSPENDIDO,IDPROVEEDOR)
SELECT * FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = 'SI';
SELECT * FROM PRODUCTOS_SUSPENDIDOS;

DELETE FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO='SI';

COMMIT;


ROLLBACK;












